//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientServerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spend
    {
        public int Id { get; set; }
        public string TotalSpend { get; set; }
        public string CallSpend { get; set; }
        public string MessageSpend { get; set; }
        public int ClientId { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
